# Generated by Django 6.0.1 on 2026-08-17 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_category_products_ca_slug_da4386_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='product-list/'),
        ),
    ]
