# Generated by Django 6.0.1 on 2026-08-20 09:10

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=products.models.ProductImage.product_image_upload_to),
        ),
    ]
